server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 85
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
#      &?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8autoReconnect=true
      url: jdbc:mysql://127.0.0.1:3306/live_shop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 745567172
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  mail:
    host: smtp.163.com
    port: 25
    default-encoding: UTF-8
    username:
    password:
  redis:
    database: 0
    host:
    port:
    password:
    lettuce:
      pool:
        max-active: 16
        min-idle: 8
        max-idle: 10
#        max-wait:



# slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别
    cn.jjvu.xiao: trace
    org.springframework.web: debug
    org.springframework.transaction: debug
    org.mybatis: debug
  file: C:/live_shop.log

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.jjvu.xiao.dao

# PageHelper 分页器
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
#  params: count=countSql


